services:
  postgres:
    image: postgres:17.2
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      B_NAME: test
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ./back-end
      dockerfile: dockerfile
    container_name: backend_app
    command: npm run dev
    volumes:
      - ./back-end:/app
      - backend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: test
      DB_PASS: test
      DB_NAME: test
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: frontend_app
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  backend_node_modules: